name: Node.js CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: ["develop", "main", "prod"]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - run: npm ci
    
    - run: npm run build --if-present
    
    - run: npm test
    
    - name: Set environment variables from secret
      run: |
        echo "${{ secrets.ENV }}" > .env
        export $(cat .env | xargs)

    - name: Run tests with environment variables
      run: npm test
      env:
        PORT: ${{ secrets.PORT }}
        MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
        MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
        MYSQL_USER: ${{ secrets.MYSQL_USER }}
        MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_COLLECTION: ${{ secrets.DB_COLLECTION }}
        MONGO_USER: ${{ secrets.MONGO_USER }}
        MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
